libp2p/js-libp2p-webrtc-star

src/webrtc-star/index.js, test/browser.js, test/webrtc-star/test-dial-and-destroy.js
This should fix (at least some) the errors you saw when a browser tab dropped, @haadcode. //cc @dignifiedquire
=> fix the close event for when a conn is destroyed

README.md, package.json, src/webrtc-star/index.js, test/webrtc-star/test-dial.js, test/webrtc-star/test-valid-connection.js
It was rather easy :) @dignifiedquire wanna CR please?
=> Migrate to pull-streams

src/signalling-server/bin.js
Not everyone has a `/usr/local/bin/node`. I have (on Ubuntu 16.04) only a `/usr/bin/node`. The current shebang just produces this:
```
$ star-sig
bash: /usr/bin/star-sig: /usr/local/bin/node: bad interpreter: No such file or directory
```
I am currently having to run
```
node `which star-sig`
```
instead.
This change uses `/usr/bin/env` to go find a `node` to run the script, which I think is best practice. Everyone *should* have a `/usr/bin/env`, the purpose of which is to solve this problem of finding your interpreter.
=> Use env to find node

.gitignore, .travis.yml, README.md, package.json, test/signalling-server/test-signalling-server.js, test/webrtc-star/test-dial.js, test/webrtc-star/test-valid-connection.js
Ref https://github.com/ipfs/js-ipfs/pull/485
=> Async Crypto Endeavour

gulpfile.js, package.json, src/signalling-server/config.js, src/signalling-server/index.js, src/webrtc-star/index.js, test/node.js, test/signalling-server/test-signalling-server.js, test/webrtc-star/test-dial.js, test/webrtc-star/test-listen.js
I'm pretty excited about getting this in, it will mean that Node.js nodes will be able to dial to browser nodes directly (perfect for relay into weird NAT'ed networks). But after I added `wrtc`, aegir started freezing on:
```
[11:09:41] Finished 'test:browser:before' after 32 ms
[11:09:41] Starting 'karma'...
```
@dignifiedquire what is the best way to debug this?
=> WebRTC support in Node.js

src/webrtc-star/index.js, test/webrtc-star/test-dial.js
Hey All,
Errors from the signaling server are not currently being handled. They are simply ignored, this PR adds error handling and a simple test to ensure this does not break in the future.
Previously without the error handling, dialing an offline node caused extremely undesirable effects, part of which was a connection being established from the initiating node to itself by the means of two different instances of SimplePeer. Then, the undesirable connection was returned to the caller of dial as the connection to the offline node.
This is also likely a part of the fix to this issue too. #5  
Thanks
=> Added signaling error handling to webrtc-star transport

README.md
Removed the mention of unsecure WebSockets connection and only left the secure one. Reason for this is that you can connect to a secure websocket from both http and https, but you can only connect to a unsecure one from http and not https, unless you want the user to accept "unsecure connection" warnings.
=> docs: Remove mention of unsecure ws connection

src/index.js, test/node.js, test/transport/reconnect.node.js
If a connection to the signalling server dies and then recovers, Socket.io emits the `connect` event again.
It happens that the peer was ignoring it. This fixes it.
=> fix: handle reconnection to signaling server

src/sig-server/config.js, src/sig-server/routes-ws/index.js, test/sig-server.js
I'm building a demo using IPFS, and when testing several scenarios, IPFS was apparently unable to recover from this:
When disconnecting the network temporarily, the WebRTC peer connections disconnect shortly after. But the WS connection to the Signaling Server lingers on for a while.
Once the network is available again, each peer does not reconnect to the other known peers.
This change on the Signaling Server allows the node to get a fresh list of peers and reconnect.
=> signaling server: send fresh peer list to each node every 10 seconds

src/utils.js, test/utils.spec.js
This is my attempt to add explicit TCP/Port support (also my first PR ever): https://github.com/libp2p/js-libp2p-webrtc-star/issues/129
- /dn4: Should work... I think. Test cases added as well.
- /ip4: Should also work, but it allows implicit TCP/Port (will look at it tomorrow, out of battery :))
- /dns6
- /ip6
Aegir gave me problems because of WebRTC.
I'm not sure if created the test cases properly. So double check that.
Some TCP/Ports are bogus, but I don't think it's actually trying to dial them, so that's ok.
Default ports probably won't show as an explicit port by design.
Regarding /ip4, is it because of https://github.com/whyrusleeping/js-mafmt/blob/9df8d849e405ef8765e09897aba6c3c89e270572/src/index.js#L26-L34? (Just guessing) …
=> Fix: /dns4 multiaddr explicit tcp/port support

README.md
I found that imports wrong module name. (electron-wrtc => electron-webrtc)
=> Fix wrong module name in usage

package.json
relates to https://github.com/libp2p/js-libp2p/pull/211
The new version of wrtc, 0.1.6, fixes an issue that was breaking usage in wrtc >= 0.1.2.
Electron-wrtc tests are still having issues (unrelated to this PR), but this gets CI another step closer to full green.
=> chore: update wrtc

src/index.js
Resolves https://github.com/ipfs/js-ipfs/issues/1561
There are issues with rtc connection cleanup in chrome, https://github.com/ipfs/js-ipfs/issues/1561#issuecomment-421080057, that result in errors being thrown when too many connections are attempted. 
This catches and logs those thrown errors as well as returning the error in the callback.
**Note**: CI errors are due to an ongoing issue with electron-wrtc.
=> fix: catch RTCPeerConnection failed connections

.aegir.js, package.json, src/sig-server/bin.js, src/sig-server/config.js, src/sig-server/index.js, test/sig-server.js, test/transport/reconnect.node.js
For security and performance reasons, Hapi updated from v16 to v18. The hapi implementation moved from callbacks to promises and the code for the signaling server was refactored to use async await instead.
Moreover, in this PR I had to throw an error if metrics are enabled as the current implementation of `epimetheus` is not compatible with the new implementation of hapi. I created an issue to track this #174  
Closes #172
=> fix: update hapi

src/index.js, test/transport/discovery.js, test/transport/reconnect.node.js
Fixes #175 
wanted to be able to disable certain discovery methods at runtime, noticed I was unable to stop this one
=> feat: start/stop discovery events when start/stop called

README.md, package.json, test/sig-server.js, test/transport/dial.js
Updated documentation.
There was an issue with CI because we could not create invalid multiaddr anymore
=> docs: multiaddr should use p2p

README.md
Per https://github.com/libp2p/js-libp2p-webrtc-star/blob/master/src/sig-server/bin.js#L11 the default port for the signalling port was wrong
=> chore: update default signaling port

package.json, src/listener.js, test/compliance.spec.js
Fixed per discussion on [libp2p/js-libp2p#523#discussion_r359997872](https://github.com/libp2p/js-libp2p/pull/523#discussion_r359997872)
=> fix: transport should not handle connection if upgradeInbound throws

package.json, src/listener.js, test/compliance.spec.js, test/transport/dial.js, test/transport/track.js
Inbound webrtc channels were being upgraded to Connections before the `connect` event was fired. When run in Node.js with wrtc this prevents us from getting the actual remoteAddress of the socket.
In the browser we cant get remoteAddress from the socket, so it is created by concatenating the signaling address with the remote peer id, and then set on the Connection before yielding it.
* I also updated the track connection test to avoid flakiness issues
* resolved some test flakiness issues via https://github.com/libp2p/js-interfaces/pull/21
=> fix: ensure remoteAddr is always set on inbound conns

package.json, src/index.js, src/listener.js, test/browser.js, test/node.js, test/transport/filter.js, test/transport/listen.js
Previously when listening on a webrtc-star multiaddr, you would also have to specify your PeerId. This PR makes it so that the PeerId will automatically be added to the multiaddrs returned from `listener.getAddrs()`.
This allows you to start libp2p with an address like `/ip4/127.0.0.1/tcp/15555/ws/p2p-webrtc-star`, and it will automatically be updated with the peer id `/ip4/127.0.0.1/tcp/15555/ws/p2p-webrtc-star/p2p/QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSooooA` for advertising.
=> feat: improve listening address usage

src/listener.js, test/browser.js, test/node.js, test/transport/listen.js
This fixes an unncessary change from #194. The transport
should not be modifying listen addresses. This was being done to overcome
an issue with mafmt not supporting all valid webrtc-star addresses,
however that was fixed and this hack wasn't reverted. This
reverts the hack to keep consistency with transport listening and
getAddrs behavior.
=> fix: dont transform listening addrs

src/index.js, src/listener.js, test/browser.js, test/node.js, test/transport/dial.js, test/transport/discovery.js, test/transport/filter.js, test/transport/listen.js, test/transport/reconnect.node.js, test/transport/track.js
- Listening multiaddrs should be returned unmodified
- multiaddrs announced over signaling must include the peer id
These were being treated as the same multiaddr, which causes problems when you are using a listening multiaddr that doesn't contain a peer id `/ip4/127.0.0.1/tcp/15555/ws/p2p-webrtc-star`, which is a more convenient way of specifying a listening multiaddr.
This PR makes these two things separate, listening vs announce multiaddrs.
The tests weren't doing a good job of validating connections. In many of the tests the same multiaddr was being used (with the exact same id), which would actually result in a peer dialing itself, and not the other peer. This PR also corrects that, which will help catch multiaddr issues like the ones this PR fixes.
=> fix: signaling vs listening addrs

src/index.js, test/transport/dial.js
`offer.err` is returned as a string, convert it to an Error.
I encountered this trying to connect to a signalling server that was not running, the error was thrown as a string.
I pulled the error code out of thin air, there might be a more appropriate one to use.
=> fix: ensure dial is rejected with an Error

src/sig-server/bin.js
Per discussion on [libp2p/js-libp2p-stardust#26](https://github.com/libp2p/js-libp2p-stardust/pull/26) this adds support for dash case parameters in the server binary runner with alias.
=> feat: support dash case parameters

src/index.js, test/compliance.spec.js, test/transport/discovery.js, test/transport/reconnect.node.js
In the context of deprecating `peer-info` as described on [libp2p/js-libp2p#589](https://github.com/libp2p/js-libp2p/issues/589), this PR changes the `peer-discovery` interface to emit an object containing an `id` property and a `multiaddrs` property.
BREAKING CHANGE: peer event emits an object with id and multiaddr instead of a peer-info
Needs:
=> chore: peer-discovery not using peer-info

src/index.js, src/listener.js, src/socket-to-conn.js
This fixes https://github.com/libp2p/js-libp2p/issues/662
This should also be cherry-picked to `0.17.x`
=> fix: add error handler for incoming connections

src/index.js
Fixes #225 
This should also be cherry-picked to 0.17.x
=> fix: do not signal if channel destroyed

package.json, src/index.js
`ipfs-utils@2.4.0` adds a `supportsWebRTCDataChannels` property which is true if the current environment supports `RTCPeerConnection`s.
Since we only use WebRTC data channels and not `getUserMedia`, switch our check over to `supportsWebRTCDataChannels` when deciding if WebRTC is supported or not.
=> fix: use relaxed webrtc check

.travis.yml, package.json
Updates Hapi to the latest version
BREAKING CHANGES:
- Hapi has dropped support for node < 12
=> chore: update deps

README.md
Old links are archived/deprecated.
=> README: Update js-libp2p-interfaces links to new repos

src/listener.js, test/transport/listen.js
Adds an error event listener and reject the promise.
=> fix: add error event listener to event emitter

src/index.js, test/transport/dial.js
Per https://github.com/ipfs/js-ipfs/pull/3633
=> chore: add err code for unknown signal server on dial

.github/workflows/main.yml, packages/transport/package.json
BREAKING CHANGE: requires node 15+
=> chore: update to new peer-id and libp2p-crypto

packages/webrtc-star-transport/src/index.ts, packages/webrtc-star-transport/test/browser.ts, packages/webrtc-star-transport/test/compliance.spec.ts, packages/webrtc-star-transport/test/node.ts, packages/webrtc-star-transport/test/transport/dial.ts, packages/webrtc-star-transport/test/transport/instance.spec.ts
Update to the latest version of libp2p interfaces
=> fix: update interfaces

Dockerfile, packages/webrtc-star-signalling-server/bin/index.js
Instead of building from source on every push, build when a GH release is created and use the built version from npm.
The GH hook in this repo has been updated accordingly.
=> fix: fix docker build

packages/webrtc-star-transport/.aegir.cjs, packages/webrtc-star-transport/package.json, packages/webrtc-star-transport/src/index.ts, packages/webrtc-star-transport/test/node.ts
Registers shutdown hook to work around double-free that causes segfaults in recent node versions.
=> chore: enable node testing

README.md
`transport` link was incorrect. Also took the opportunity to add a
reference to the `protocol` package.
=> fix: Readme link

packages/webrtc-star-signalling-server/src/index.ts
`__dirname` is not available in ESM environments, we have to derive it from the import metadata.
Fixes #409
=> fix: define __dirname

.gitignore, packages/webrtc-star-signalling-server/src/index.ts, packages/webrtc-star-signalling-server/src/socket-server.ts, packages/webrtc-star-transport/package.json, packages/webrtc-star-transport/src/index.ts, packages/webrtc-star-transport/src/listener.ts, packages/webrtc-star-transport/test/browser.ts, packages/webrtc-star-transport/test/index.ts, packages/webrtc-star-transport/test/node.ts, packages/webrtc-star-transport/test/transport/dial.ts, packages/webrtc-star-transport/test/transport/discovery.ts, packages/webrtc-star-transport/test/transport/filter.ts, packages/webrtc-star-transport/test/transport/listen.ts, packages/webrtc-star-transport/test/transport/multiple-signal-servers.ts, packages/webrtc-star-transport/test/transport/reconnect.node.ts, packages/webrtc-star-transport/test/transport/track.ts
Tweaks the logic around server errors so that if we lose our connection to the sigserver, we now let socket.io's reconnection logic handle trying to reconnect instead of emitting an error that causes everything to be torn down.
Fixes: #453
=> fix: do not close connections when sigserver goes away

packages/webrtc-star-transport/package.json, packages/webrtc-star-transport/src/index.ts, packages/webrtc-star-transport/test/browser.ts, packages/webrtc-star-transport/test/compliance.spec.ts, packages/webrtc-star-transport/test/node.ts, packages/webrtc-star-transport/test/transport/instance.spec.ts
`@libp2p/components` is a choke-point for our dependency graph as it depends on every interface, meaning when one interface revs a major `@libp2p/components` major has to change too which means every module depending on it also needs a major.
Switch instead to constructor injection of simple objects that let modules declare their dependencies on interfaces directly instead of indirectly via `@libp2p/components`
Refs https://github.com/libp2p/js-libp2p-components/issues/6
BREAKING CHANGE: modules no longer implement `Initializable` instead switching to constructor injection
=> fix!: remove @libp2p/components

packages/webrtc-star-transport/README.md, packages/webrtc-star-transport/src/index.ts, packages/webrtc-star-transport/test/compliance.spec.ts, packages/webrtc-star-transport/test/transport/discovery.ts, packages/webrtc-star-transport/test/transport/reconnect.node.ts
To use the same interface as other libp2p components, expose the discovery module as a factory function.
=> fix: expose discovery as factory
